app/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_user, logout_user, login_required, current_user
from werkzeug.security import generate_password_hash, check_password_hash
from app import db
from app.models import User
from app.forms import LoginForm, RegisterForm

auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and check_password_hash(user.password, form.password.data):
            login_user(user)
            if user.is_manager:
                return redirect(url_for('main.manager_dashboard'))
            return redirect(url_for('main.index'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', form=form)

@auth.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        hashed_password = generate_password_hash(form.password.data, method='pbkdf2:sha256')
        is_manager = form.manager_password.data == 'test'
        new_user = User(email=form.email.data, password=hashed_password, name=form.name.data, is_manager=is_manager)
        db.session.add(new_user)
        db.session.commit()
        login_user(new_user)
        return redirect(url_for('main.index'))
    return render_template('register.html', form=form)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

app/views.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, send_file, jsonify
from flask_login import login_user, logout_user, login_required, current_user
from app import db
import io, csv
from datetime import datetime
from app.models import User, Client, Task, OnboardingTask, ContentIdea, Metric, Notification
from app.forms import ClientForm, OnboardingTaskForm, ContentIdeaForm, MetricForm, TaskForm, TaskSubmissionForm, LoginForm, RegisterForm

main = Blueprint('main', __name__)

def get_unread_notification_count(user_id):
    return Notification.query.filter_by(user_id=user_id, read=False).count()

@main.context_processor
def inject_notification_count():
    if current_user.is_authenticated:
        unread_notification_count = get_unread_notification_count(current_user.id)
        return {'unread_notification_count': unread_notification_count}
    return {'unread_notification_count': 0}

@main.route('/')
@login_required
def index():
    if current_user.is_manager:
        return redirect(url_for('main.manager_dashboard'))
    else:
        return redirect(url_for('main.worker_dashboard'))

@main.route('/manager_dashboard')
@login_required
def manager_dashboard():
    if not current_user.is_manager:
        return redirect(url_for('main.index'))
    
    active_clients_count = Client.query.filter_by(status='Active').count()
    completed_tasks_count = Task.query.filter_by(status='Completed').count()
    assigned_tasks_count = Task.query.filter_by(status='Assigned').count()
    in_progress_tasks_count = Task.query.filter_by(status='In Progress').count()

    return render_template('manager_dashboard.html', 
                           active_clients_count=active_clients_count,
                           completed_tasks_count=completed_tasks_count,
                           assigned_tasks_count=assigned_tasks_count,
                           in_progress_tasks_count=in_progress_tasks_count)




@main.route('/worker_dashboard')
@login_required
def worker_dashboard():
    pending_tasks_count = Task.query.filter_by(worker_id=current_user.id, status='Assigned').count()
    in_progress_tasks_count = Task.query.filter_by(worker_id=current_user.id, status='In Progress').count()
    completed_tasks_count = Task.query.filter_by(worker_id=current_user.id, status='Completed').count()
    average_completion_time = db.session.query(db.func.avg(Task.completion_time)).filter_by(worker_id=current_user.id).scalar()
    return render_template('worker_dashboard.html', pending_tasks_count=pending_tasks_count, in_progress_tasks_count=in_progress_tasks_count, completed_tasks_count=completed_tasks_count, average_completion_time=average_completion_time) 

@main.route('/notifications')
@login_required
def notifications():
    notifications = Notification.query.filter_by(user_id=current_user.id, read=False).order_by(Notification.timestamp.desc()).all()
    return render_template('notifications.html', notifications=notifications)

@main.route('/mark_notification_as_read/<int:notification_id>')
@login_required
def mark_notification_as_read(notification_id):
    notification = Notification.query.get_or_404(notification_id)
    notification.read = True
    db.session.commit()
    return redirect(url_for('main.notifications'))

@main.route('/clients')
@login_required
def clients():
    if current_user.is_manager:
        clients = Client.query.all()
    else:
        clients = Client.query.filter_by(user_id=current_user.id).all()
    return render_template('clients.html', clients=clients)

@main.route('/client/<int:client_id>')
@login_required
def client_profile(client_id):
    client = Client.query.get_or_404(client_id)
    tasks = Task.query.filter_by(client_id=client_id).all()
    onboarding_tasks = OnboardingTask.query.filter_by(client_id=client_id).all()
    content_ideas = ContentIdea.query.filter_by(client_id=client_id).all()
    metrics = Metric.query.filter_by(client_id=client_id).all()
    return render_template('client_profile.html', client=client, tasks=tasks, onboarding_tasks=onboarding_tasks, content_ideas=content_ideas, metrics=metrics)


@main.route('/assign_task', methods=['GET', 'POST'])
@login_required
def assign_task():
    form = TaskForm()
    
    # Populate worker email dropdown with non-manager users
    form.worker_email.choices = [(user.email, user.email) for user in User.query.filter_by(is_manager=False).all()]
    
    # Populate client dropdown with clients
    form.client_id.choices = [(client.id, client.name) for client in Client.query.all()]

    if form.validate_on_submit():
        worker = User.query.filter_by(email=form.worker_email.data).first()
        if worker:
            new_task = Task(
                manager_id=current_user.id,
                worker_id=worker.id,
                client_id=form.client_id.data,
                task_description=form.task_description.data,
                deadline=form.deadline.data,
                status='Assigned'
            )
            db.session.add(new_task)
            db.session.commit()
            
            # Create notification for the worker
            notification = Notification(
                user_id=worker.id,
                message=f'You have been assigned a new task: {new_task.task_description}',
                type='task_assigned'
            )
            db.session.add(notification)
            
            # Create notification for managers
            managers = User.query.filter_by(is_manager=True).all()
            for manager in managers:
                notification = Notification(
                    user_id=manager.id,
                    message=f'A new task has been assigned to {worker.name}',
                    type='task_assigned'
                )
                db.session.add(notification)
                
            db.session.commit()
            
            flash('Task assigned successfully!', 'success')
            return redirect(url_for('main.kanban_board'))
        else:
            flash('Worker not found.', 'danger')
    return render_template('assign_task.html', form=form)



@main.route('/submit_task/<int:task_id>', methods=['GET', 'POST'])
@login_required
def submit_task(task_id):
    task = Task.query.get_or_404(task_id)
    form = TaskSubmissionForm()
    if form.validate_on_submit():
        task.status = 'Completed'
        task.completion_description = form.completion_description.data
        task.completion_link = form.completion_link.data
        task.completion_time = datetime.now()
        db.session.commit()
        
        # Create notification for the manager
        notification = Notification(
            user_id=task.manager_id,
            message=f'Task "{task.task_description}" has been completed by {task.worker.name}',
            type='task_completed'
        )
        db.session.add(notification)
        db.session.commit()
        
        flash('Task submitted successfully!', 'success')
        return redirect(url_for('main.kanban_board'))
    return render_template('submit_task.html', form=form)


@main.route('/add_client', methods=['GET', 'POST'])
@login_required
def add_client():
    form = ClientForm()
    if form.validate_on_submit():
        new_client = Client(
            user_id=current_user.id,
            name=form.name.data,
            contact_number=form.contact_number.data,
            business_category=form.business_category.data,
            social_media_handles=form.social_media_handles.data,
            goals=form.goals.data,
            specific_requests=form.specific_requests.data
        )
        db.session.add(new_client)
        db.session.commit()
        
        # Create notification for managers
        managers = User.query.filter_by(is_manager=True).all()
        for manager in managers:
            notification = Notification(
                user_id=manager.id,
                message=f'A new client "{new_client.name}" has been added by {current_user.name}',
                type='client_added'
            )
            db.session.add(notification)
        db.session.commit()
        
        flash('Client added successfully!', 'success')
        return redirect(url_for('main.clients'))
    return render_template('add_client.html', form=form)

@main.route('/add_onboarding_task/<int:client_id>', methods=['GET', 'POST'])
@login_required
def add_onboarding_task(client_id):
    form = OnboardingTaskForm()
    if form.validate_on_submit():
        new_task = OnboardingTask(
            client_id=client_id,
            task_name=form.task_name.data,
            responsible=form.responsible.data,
            deadline=form.deadline.data
        )
        db.session.add(new_task)
        db.session.commit()
        
        # Create notification for managers
        managers = User.query.filter_by(is_manager=True).all()
        for manager in managers:
            notification = Notification(
                user_id=manager.id,
                message=f'A new onboarding task "{new_task.task_name}" has been added for client ID {client_id}',
                type='onboarding_task_added'
            )
            db.session.add(notification)
        db.session.commit()
        
        flash('Onboarding task added successfully!', 'success')
        return redirect(url_for('main.client_profile', client_id=client_id))
    return render_template('add_onboarding_task.html', form=form)

@main.route('/add_content_idea/<int:client_id>', methods=['GET', 'POST'])
@login_required
def add_content_idea(client_id):
    form = ContentIdeaForm()
    if form.validate_on_submit():
        new_idea = ContentIdea(
            client_id=client_id,
            idea_source=form.idea_source.data,
            description=form.description.data,
            link=form.link.data,
            sound=form.sound.data,
            status=form.status.data
        )
        db.session.add(new_idea)
        db.session.commit()
        

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Guidely SMMA{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <meta name="csrf-token" content="{{ csrf_token() }}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark">
        <a class="navbar-brand" href="{{ url_for('main.index') }}">Guidely SMMA</a>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto">
                {% if current_user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('main.index') }}">Home</a></li>
                    {% if current_user.is_manager %}
                        <li class="nav-item"><a class="nav-link" href="{{ url_for('main.manager_dashboard') }}">Dashboard</a></li>
                        <li class="nav-item"><a class="nav-link" href="{{ url_for('main.clients') }}">Clients</a></li>
                        <li class="nav-item"><a class="nav-link" href="{{ url_for('main.kanban_board') }}">Kanban Board</a></li>
                        <li class="nav-item"><a class="nav-link" href="{{ url_for('main.task_list') }}">Task List</a></li>
                        <li class="nav-item"><a class="nav-link" href="{{ url_for('main.submitted_tasks') }}">Submitted Tasks</a></li>
                        <li class="nav-item"><a class="nav-link" href="{{ url_for('main.submitted_tasks_report') }}">report</a></li>
                    {% else %}
                        <li class="nav-item"><a class="nav-link" href="{{ url_for('main.kanban_board') }}">Kanban Board</a></li>
                        <li class="nav-item"><a class="nav-link" href="{{ url_for('main.worker_dashboard') }}">Dashboard</a></li>
                        <li class="nav-item"><a class="nav-link" href="{{ url_for('main.task_list') }}">Task List</a></li>
                    {% endif %}
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('main.forms') }}">Forms</a></li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.notifications') }}">
                            Notifications
                            <span class="badge badge-danger">{{ unread_notification_count }}</span>
                        </a>
                    </li>
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a></li>
                {% else %}
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.login') }}">Login</a></li>
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.register') }}">Register</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
    <footer>
        <p>&copy; Guidely SMMA. All rights reserved.</p>
    </footer>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    {% block scripts %}{% endblock %}
</body>
</html>

app/templates/client_profile.html
{% extends "base.html" %}

{% block title %}
Client Profile - {{ client.name }}
{% endblock %}

{% block content %}
<div class="container mt-5">
    <h1 class="text-center mb-4">Client Profile: {{ client.name }}</h1>

    <div class="card mt-3 bg-white text-black">
        <div class="card-header bg-primary text-white">
            <h3>Client Information</h3>
        </div>
        <div class="card-body">
            <p><strong>ID:</strong> {{ client.id }}</p>
            <p><strong>Name:</strong> {{ client.name }}</p>
            <p><strong>Contact Number:</strong> {{ client.contact_number }}</p>
            <p><strong>Business Category:</strong> {{ client.business_category }}</p>
            <p><strong>Social Media Handles:</strong> {{ client.social_media_handles }}</p>
            <p><strong>Goals:</strong> {{ client.goals }}</p>
            <p><strong>Specific Requests:</strong> {{ client.specific_requests }}</p>
        </div>
    </div>

    <div class="card mt-3 bg-white text-black">
        <div class="card-header bg-primary text-white d-flex justify-content-between">
            <h3>Onboarding Tasks</h3>
            <div>
                <a class="btn btn-secondary" href="{{ url_for('main.download_onboarding_tasks', client_id=client.id) }}">Download</a>
                <a class="btn btn-primary" href="{{ url_for('main.add_onboarding_task', client_id=client.id) }}">Add</a>
            </div>
        </div>
        <div class="card-body">
            {% if onboarding_tasks %}
                <table class="table table-striped table-bordered bg-white text-black">
                    <thead>
                        <tr>
                            <th>Task Name</th>
                            <th>Responsible</th>
                            <th>Deadline</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for task in onboarding_tasks %}
                            <tr>
                                <td>{{ task.task_name }}</td>
                                <td>{{ task.responsible }}</td>
                                <td>{{ task.deadline }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>No onboarding tasks found.</p>
            {% endif %}
        </div>
    </div>

    <div class="card mt-3 bg-white text-black">
        <div class="card-header bg-primary text-white d-flex justify-content-between">
            <h3>Content Ideas</h3>
            <div>
                <a class="btn btn-secondary" href="{{ url_for('main.download_content_ideas', client_id=client.id) }}">Download</a>
                <a class="btn btn-primary" href="{{ url_for('main.add_content_idea', client_id=client.id) }}">Add</a>
            </div>
        </div>
        <div class="card-body">
            {% if content_ideas %}
                <table class="table table-striped table-bordered bg-white text-black">
                    <thead>
                        <tr>
                            <th>Idea Source</th>
                            <th>Description</th>
                            <th>Link</th>
                            <th>Sound</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for idea in content_ideas %}
                            <tr>
                                <td>{{ idea.idea_source }}</td>
                                <td>{{ idea.description }}</td>
                                <td><a href="{{ idea.link }}" target="_blank">{{ idea.link }}</a></td>
                                <td>{{ idea.sound }}</td>
                                <td>{{ idea.status }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>No content ideas found.</p>
            {% endif %}
        </div>
    </div>

    <div class="card mt-3 bg-white text-black">
        <div class="card-header bg-primary text-white d-flex justify-content-between">
            <h3>Metrics</h3>
            <div>
                <a class="btn btn-secondary" href="{{ url_for('main.download_metrics', client_id=client.id) }}">Download</a>
                <a class="btn btn-primary" href="{{ url_for('main.add_metric', client_id=client.id) }}">Add</a>
            </div>
        </div>
        <div class="card-body">
            {% if metrics %}
                <table class="table table-striped table-bordered bg-white text-black">
                    <thead>
                        <tr>
                            <th>Platform</th>
                            <th>Post Date</th>
                            <th>Views</th>
                            <th>Likes</th>
                            <th>Comments</th>
                            <th>Shares</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for metric in metrics %}
                            <tr>
                                <td>{{ metric.platform }}</td>
                                <td>{{ metric.post_date }}</td>
                                <td>{{ metric.views }}</td>
                                <td>{{ metric.likes }}</td>
                                <td>{{ metric.comments }}</td>
                                <td>{{ metric.shares }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>No metrics found.</p>
            {% endif %}
        </div>
    </div>

    <div class="card mt-3 bg-white text-black">
        <div class="card-header bg-primary text-white d-flex justify-content-between">
            <h3>Tasks</h3>
            <div>
                <a class="btn btn-secondary" href="{{ url_for('main.download_tasks') }}">Download</a>
                <a class="btn btn-primary" href="{{ url_for('main.assign_task', client_id=client.id) }}">Assign</a>
            </div>
        </div>
        <div class="card-body">
            {% if tasks %}
                <table class="table table-striped table-bordered bg-white text-black">
                    <thead>
                        <tr>
                            <th>Task Description</th>
                            <th>Assigned To</th>
                            <th>Deadline</th>
                            <th>Status</th>
                            <th>Completion Description</th>
                            <th>Completion Link</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for task in tasks %}
                            <tr>
                                <td>{{ task.task_description }}</td>
                                <td>{{ task.assigned_worker.name }}</td>
                                <td>{{ task.deadline }}</td>
                                <td>{{ task.status }}</td>
                                {% if task.status == 'Completed' %}
                                    <td>{{ task.completion_description }}</td>
                                    <td><a href="{{ task.completion_link }}" target="_blank">{{ task.completion_link }}</a></td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>No tasks found.</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

app/templates/clients.html
{% extends "base.html" %}

{% block title %}Clients{% endblock %}

{% block content %}
<h1>Clients</h1>
<a class="btn btn-primary" href="{{ url_for('main.download_clients') }}">Download Clients</a>
<a class="btn btn-secondary" href="{{ url_for('main.add_client') }}">Add Client</a>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Contact Number</th>
            <th>Business Category</th>
            <th>Social Media Handles</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for client in clients %}
        <tr>
            <td><a href="{{ url_for('main.client_profile', client_id=client.id) }}">{{ client.name }}</a></td>
            <td>{{ client.contact_number }}</td>
            <td>{{ client.business_category }}</td>
            <td>{{ client.social_media_handles }}</td>
            <td>
                <a class="btn btn-primary btn-sm" href="{{ url_for('main.client_profile', client_id=client.id) }}">View</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

app/templates/dashboard.html
{% extends "base.html" %}

{% block title %}Dashboard{% endblock %}

{% block content %}
<h1>Dashboard</h1>
{% if current_user.is_manager %}
<h2>Assigned Tasks</h2>
<table class="table table-dark table-striped">
    <thead>
        <tr>
            <th>Client ID</th>
            <th>Task Description</th>
            <th>Deadline</th>
            <th>Status</th>
            <th>Completion Description</th>
            <th>Completion Link</th>
        </tr>
    </thead>
    <tbody>
        {% for task in tasks %}
        <tr>
            <td>{{ task.client_id }}</td>
            <td>{{ task.task_description }}</td>
            <td>{{ task.deadline }}</td>
            <td>{{ task.status }}</td>
            <td>{{ task.completion_description }}</td>
            <td><a href="{{ task.completion_link }}" target="_blank">{{ task.completion_link }}</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<h2>Your Tasks</h2>
<table class="table table-dark table-striped">
    <thead>
        <tr>
            <th>Client ID</th>
            <th>Task Description</th>
            <th>Deadline</th>
            <th>Status</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for task in tasks %}
        <tr>
            <td>{{ task.client_id }}</td>
            <td>{{ task.task_description }}</td>
            <td>{{ task.deadline }}</td>
            <td>{{ task.status }}</td>
            <td>
                {% if task.status == 'Assigned' %}
                <a class="btn btn-primary" href="{{ url_for('main.submit_task', task_id=task.id) }}">Submit Task</a>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endif %}
{% endblock %}

app/templates/notifications.html
{% extends "base.html" %}

{% block title %}Notifications{% endblock %}

{% block content %}
<h1>Notifications</h1>
<ul class="list-group">
    {% for notification in notifications %}
        <li class="list-group-item {% if not notification.read %}font-weight-bold{% endif %}">
            {{ notification.message }}
            <a href="{{ url_for('main.mark_notification_as_read', notification_id=notification.id) }}" class="btn btn-sm btn-link">Mark as read</a>
        </li>
    {% endfor %}
</ul>
{% endblock %}

app/templates/register.html
{% extends "base.html" %}

{% block title %}Register{% endblock %}

{% block content %}
<div class="d-flex justify-content-center align-items-center" style="min-height: 80vh;">
    <div class="card">
        <div class="card-header">
            <h3>Register</h3>
        </div>
        <div class="card-body">
            <form method="POST" action="{{ url_for('auth.register') }}">
                {{ form.hidden_tag() }}
                <div class="form-group">
                    {{ form.name.label(class="form-control-label") }}
                    {{ form.name(class="form-control") }}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {{ form.email(class="form-control") }}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {{ form.password(class="form-control") }}
                </div>
                <div class="form-group">
                    {{ form.manager_password.label(class="form-control-label") }}
                    {{ form.manager_password(class="form-control") }}
                </div>
                <div class="form-group">
                    {{ form.submit(class="btn btn-primary btn-block") }}
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

app/templates/task_list.html
{% extends "base.html" %}

{% block title %}Task List{% endblock %}

{% block content %}
<h1>Task List</h1>

{% if current_user.is_manager %}
<div class="mb-3">
    <a class="btn btn-primary" href="{{ url_for('main.assign_task') }}">Assign Task</a>
</div>
{% endif %}


{% if is_worker and selected_task %}
    <form action="{{ url_for('main.submit_task', task_id=selected_task.id) }}" method="POST">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.completion_description.label(class="form-label") }}
            {{ form.completion_description(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.completion_link.label(class="form-label") }}
            {{ form.completion_link(class="form-control") }}
        </div>
        <button type="submit" class="btn btn-primary">Submit Task</button>
    </form>
{% endif %}

{% if tasks %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Task Description</th>
                <th>Assigned To</th>
                <th>Deadline</th>
                <th>Status</th>
                {% if not is_worker %}
                    <th>Actions</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for task in tasks %}
                <tr>
                    <td>{{ task.task_description }}</td>
                    <td>{{ task.assigned_worker.name }}</td>
                    <td>{{ task.deadline }}</td>
                    <td>{{ task.status }}</td>
                    {% if not is_worker %}
                        <td>
                            <a class="btn btn-primary btn-sm" href="{{ url_for('main.assign_task', task_id=task.id) }}">Reassign</a>
                        </td>
                    {% endif %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% else %}
    <p>No tasks found.</p>
{% endif %}
{% endblock %}

<script>
    document.addEventListener('DOMContentLoaded', function () {
        const kanbanTasks = document.querySelectorAll('.kanban-task');
    
        kanbanTasks.forEach(task => {
            task.setAttribute('draggable', true);
    
            task.addEventListener('dragstart', function (e) {
                e.dataTransfer.setData('text/plain', e.target.dataset.taskId);
            });
        });
    
        const columns = document.querySelectorAll('.kanban-column');
    
        columns.forEach(column => {
            column.addEventListener('dragover', function (e) {
                e.preventDefault();
            });
    
            column.addEventListener('drop', function (e) {
                const taskId = e.dataTransfer.getData('text/plain');
                const taskElement = document.querySelector(`[data-task-id='${taskId}']`);
                this.querySelector('.kanban-tasks').appendChild(taskElement);
    
                const status = this.querySelector('h2').innerText;
                fetch(`/tasks/${taskId}/update_status`, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                    },
                    body: JSON.stringify({ status: status })
                }).then(response => response.json())
                  .then(data => {
                      if (data.success) {
                          console.log('Task status updated successfully');
                      } else {
                          console.error('Failed to update task status');
                      }
                  });
            });
        });
    });
    </script>
    